name: clang-format

on: [pull_request]

jobs:
  job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run clang-format style check.
        uses: jidicula/clang-format-action@v4.6.0
